[package]
name = "nskeyedunarchiver"
version = "0.1.0"
edition = "2021"
authors = ["Michael Wright <maiklpolkovnikov@gmail.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1.6.0"
thiserror = "1.0.56"
