[package]
name = "nskeyedarchive_converter"
description = "Convert NSKeyedArchive encoded plists to human readable ones"
version = "0.1.0"
edition = "2021"
authors = ["Michael Wright <maiklpolkovnikov@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
plist = "1.6.0"
thiserror = "1.0.56"

[profile.release]
strip = true
